name: ci

on:
        push:
        pull_request:
jobs:
        main:
                runs-on: ubuntu-20.04
                steps:
                -
                        name: git clone alejandro-colomar/containers
                        run: |
                                sudo git -C /usr/local/src \
                                        clone --single-branch --branch 'v0.4.1' \
                                        http://github.com/alejandro-colomar/containers.git;
                -
                        name: make swarm
                        run: sudo make -C /usr/local/src/containers swarm;
                -
                        name: checkout
                        uses: actions/checkout@v2
                -
                        name: make image-build
                        run: make image-build lbl=ci;
                -
                        name: docker swarm init
                        run: docker swarm init --advertise-addr lo;
                -
                        name: make stack-deploy
                        run: sudo make stack-deploy node_role=manager;
                -
                        name: make test
                        run: make test;
